name: OSPS-AC-01.01 - Check branch protection

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: read-all

jobs:
  verify-default-ruleset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (if needed)
        uses: actions/checkout@v4

      - name: Fetch and verify default branch ruleset
        uses: actions/github-script@v7
        with:
          script: |
            // Fetch all repository rulesets for the repository
            const response = await github.request('GET /repos/{owner}/{repo}/rulesets', {
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            const rulesets = response.data;
            core.info(`Found ${rulesets.length} rulesets.`);
            
            // Find a ruleset whose conditions include "~DEFAULT_BRANCH"
            const defaultRuleset = rulesets.find(rs => {
              return rs.conditions &&
                     rs.conditions.ref_name &&
                     Array.isArray(rs.conditions.ref_name.include) &&
                     rs.conditions.ref_name.include.includes("~DEFAULT_BRANCH");
            });
            
            if (!defaultRuleset) {
              core.setFailed("No ruleset exists for the default branch (missing '~DEFAULT_BRANCH' in conditions).");
              return;
            }
            
            // Look for a pull_request rule in the found ruleset
            const prRule = defaultRuleset.rules.find(rule => rule.type === "pull_request");
            if (!prRule) {
              core.setFailed("The default branch ruleset does not contain a pull_request rule.");
              return;
            }
            
            // Check that the pull_request rule requires exactly one approving review
            if (!prRule.parameters || prRule.parameters.required_approving_review_count !== 1) {
              core.setFailed("The pull_request rule for the default branch does not require exactly one approving review.");
              return;
            }
            
            core.info("Default branch ruleset verified: it includes a pull_request rule requiring one approving review.");
